Agricultura_Precisao/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from rest_framework import routers

from Agricultura_Precisao import views

router = routers.DefaultRouter()
router.register(r'users', views.UserViewSet)
router.register(r'sensorVal', views.sensorValViewSet)

urlpatterns = [
    url(r'webservices/', include(router.urls)),
    url(r'^admin/', admin.site.urls),
    url(r'^$', views.index, name='index'),
    url(r'^login', views.login, name='login'),
    url(r'^index', views.index, name='index'),
    url(r'^AgriculturaPrecisao', views.agricprecisao, name='agricprecisao'),
    url(r'^validate_login', views.validate_login, name='validate_login'),
    url(r'^logout', views.logout, name='logout'),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest-framework')),
    url(r'^Perfil', views.perfil, name='perfil'),
    url(r'^update_profile$', views.update_profile, name='update_profile'),
    url(r'^realtime', views.realtime, name='realtime'),
    url(r'^get_100values', views.get_100values, name='get_100values'),
    url(r'^get_1000values', views.get_1000values, name='get_1000values'),
    url(r'^get_customintervalvalues', views.get_customintervalvalues, name='get_customintervalvalues'),
    url(r'^get_customdayvalues', views.get_customdayvalues, name='get_customdayvalues'),
    url(r'^get_typesensor', views.get_typesensor, name='get_typesensor'),
    url(r'^appkeys', views.appkeys, name='appkeys'),
    url(r'^alert', views.alert, name='alert'),
    url(r'^navbar', views.navbar, name='navbar'),
    url(r'^config', views.config, name='config'),
    url(r'^test', views.test, name='test'),
    url(r'^validate_password$', views.validate_password, name='validate_password'),

    # url(r'collapse/(?P<collapseid>[0-9])', views.collapse, name='collapse1'),

]

Agricultura_Precisao/models.py
# This is an auto-generated Django model module.
# You'll have to do the following manually to clean this up:
#   * Rearrange models' order
#   * Make sure each model has one field with primary_key=True
#   * Make sure each ForeignKey has `on_delete` set to the desired behavior.
#   * Remove `managed = False` lines if you wish to allow Django to create, modify, and delete the table
# Feel free to rename the models, but don't rename db_table values or field names.
from __future__ import unicode_literals

from django.db import models


class Alert(models.Model):
    alertid = models.IntegerField(db_column='alertid', primary_key=True)
    timestampalert = models.DateTimeField(db_column='timestampAlert')  # Field name made lowercase.
    valuealert = models.FloatField(db_column='valueAlert', blank=True, null=True)  # Field name made lowercase.
    sensorfk = models.ForeignKey('Sensor', models.DO_NOTHING, db_column='sensorFk', blank=True, null=True)  # Field name made lowercase.
    state = models.IntegerField()
    dresciption = models.CharField(max_length=100, blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'alert'


class Appkey(models.Model):
    appkeyid = models.AutoField(db_column='appKeyId', primary_key=True)  # Field name made lowercase.
    appkey = models.CharField(db_column='appKey', unique=True, max_length=100)  # Field name made lowercase.
    userid = models.ForeignKey('User', models.DO_NOTHING, db_column='userId')  # Field name made lowercase.

    class Meta:
        managed = False
        db_table = 'appkey'


class Communicationtype(models.Model):
    idtype = models.AutoField(db_column='idType', primary_key=True)  # Field name made lowercase.
    typecommunicationname = models.CharField(db_column='typeCommunicationName', unique=True, max_length=50)  # Field name made lowercase.

    class Meta:
        managed = False
        db_table = 'communicationtype'


class Sensor(models.Model):
    sensorid = models.AutoField(db_column='sensorId', primary_key=True)  # Field name made lowercase.
    waspmoteid = models.ForeignKey('Waspmote', models.DO_NOTHING, db_column='waspmoteId')  # Field name made lowercase.
    typesensorid = models.ForeignKey('Typesensor', models.DO_NOTHING, db_column='typeSensorId')  # Field name made lowercase.
    status = models.IntegerField()


    class Meta:
        managed = False
        db_table = 'sensor'


class Sensorval(models.Model):
    sensorvalid = models.AutoField(db_column='sensorValID', primary_key=True)  # Field name made lowercase.
    value = models.FloatField()
    sensor_fk = models.ForeignKey(Sensor, models.DO_NOTHING, db_column='sensor_FK')  # Field name made lowercase.
    timestamp = models.DateTimeField()

    class Meta:
        managed = False
        db_table = 'sensorval'


class Standardparameter(models.Model):
    standardid = models.AutoField(db_column='standardId', primary_key=True)  # Field name made lowercase.
    defaultmax = models.FloatField(db_column='defaultMax')  # Field name made lowercase.
    defaultmediummax = models.FloatField(db_column='defaultMediumMax')  # Field name made lowercase.
    defaultmin = models.FloatField(db_column='defaultMin')  # Field name made lowercase.
    defaultmediummin = models.FloatField(db_column='defaultMediumMin')  # Field name made lowercase.
    typeharvest = models.CharField(db_column='typeHarvest', max_length=50)  # Field name made lowercase.
    sensorfk = models.ForeignKey(Sensor, models.DO_NOTHING, db_column='sensorfk', blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'standardparameter'


class Typesensor(models.Model):
    typesensorid = models.AutoField(db_column='typeSensorId', primary_key=True)  # Field name made lowercase.
    typesensorname = models.CharField(db_column='typeSensorName', max_length=40)  # Field name made lowercase.
    maxval = models.FloatField(db_column='maxVal')  # Field name made lowercase.
    minval = models.FloatField(db_column='minVal')  # Field name made lowercase.
    sensornamelib = models.CharField(max_length=40)

    class Meta:
        managed = False
        db_table = 'typesensor'


class User(models.Model):
    iduser = models.AutoField(db_column='idUser', primary_key=True)  # Field name made lowercase.
    username = models.CharField(max_length=40)
    password = models.CharField(max_length=40)
    name = models.CharField(max_length=45)
    mail = models.CharField(max_length=40)
    country = models.CharField(max_length=40)
    city = models.CharField(max_length=40)
    phone = models.IntegerField()
    reference = models.IntegerField()

    class Meta:
        managed = False
        db_table = 'user'


class Waspmote(models.Model):
    waspmoteid = models.AutoField(db_column='waspmoteId', primary_key=True)  # Field name made lowercase.
    macaddress = models.CharField(db_column='macAddress', unique=True, max_length=50)  # Field name made lowercase.
    appkeyid = models.ForeignKey(Appkey, models.DO_NOTHING, db_column='appKeyId')  # Field name made lowercase.
    idtype = models.ForeignKey(Communicationtype, models.DO_NOTHING, db_column='idType')  # Field name made lowercase.
    waspmote_name = models.CharField(max_length=20)
    waspbatlvl = models.IntegerField()

    class Meta:
        managed = False
        db_table = 'waspmote'

Agricultura_Precisao/views.py
# Create your views here.


import json
import re

from django.core import serializers
from django.core.urlresolvers import reverse
from django.http import HttpResponse
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.views.decorators.csrf import csrf_exempt
from rest_framework import viewsets

from Agricultura_Precisao.models import Waspmote, User, Appkey, Sensorval, Typesensor, Sensor, Alert
from Agricultura_Precisao.serializers import UserSerializer, SensorValSerializer, TypeSensorSerializer


def index(request):
    return render(request, 'index.html')


def login(request):
    return render(request, 'login.html')


@csrf_exempt
def update_profile(request):
    if request.is_ajax():
        if request.method == 'POST':
            reference = request.POST.get('key')
            value = request.POST.get('value')
            username = request.POST.get('user')
            user = User.objects.get(username=username);
            if reference == 'password':
                user.password = value
            elif reference == 'mail':
                user.mail = value
            elif reference == 'country':
                user.country = value
            elif reference == 'city':
                user.city = value
            elif reference == 'phone':
                user.phone = value
            else:
                return HttpResponse("error")
            user.save()
    return HttpResponse("success")


@csrf_exempt
def validate_password(request):
    if request.is_ajax():
        if request.method == 'POST':
            username = request.POST.get('user')
            pwd = request.POST.get('password')
            user = User.objects.get(username=username)
            if user.password == pwd:
                return HttpResponse(status=200)
            else:
                return HttpResponse(status=400)


def perfil(request):
    id = User.objects.get(iduser=request.session['userID']).iduser
    username = User.objects.get(iduser=request.session['userID']).username
    password = User.objects.get(iduser=request.session['userID']).password
    name = User.objects.get(iduser=request.session['userID']).name
    country = User.objects.get(iduser=request.session['userID']).country
    city = User.objects.get(iduser=request.session['userID']).city
    mail = User.objects.get(iduser=request.session['userID']).mail
    phone = User.objects.get(iduser=request.session['userID']).phone
    appk = Appkey.objects.filter(userid=request.session['userID'])
    context = {'appk': appk, 'id': id, 'username': username, 'name': name, 'password': password, 'country': country,
               'city': city, 'mail': mail, 'phone': phone}
    return render(request, 'Perfil.html', context)


def alert(request):
    alerts = []
    waspmotealert = []

    for app in Appkey.objects.filter(userid=request.session['userID']):
        waspmote = Waspmote.objects.filter(appkeyid=app.appkeyid)
        waspmotealert += Waspmote.objects.filter(appkeyid=app.appkeyid)
        for wasp in waspmote:
            sen = Sensor.objects.filter(waspmoteid=wasp.waspmoteid)
            for alertsSensores in sen:
                alerts += Alert.objects.filter(sensorfk=alertsSensores.sensorid)

    context = {'waspmoteAlert': waspmotealert, 'alerts': alerts}
    return render(request, 'Alert.html', context)


def agricprecisao(request):
    appkeyid = request.GET.get('appId')
    waspmote_info = Waspmote.objects.filter(appkeyid=appkeyid)
    aux = None
    flag = False
    array = dict()

    for wasp in waspmote_info:
        for sensor in wasp.sensor_set.all():
            if sensor.status == 0:
                aux = 0
                break
            elif sensor.status == 1:
                aux = 1
                flag = True
            elif sensor.status == 2:
                if not flag:
                    aux = 2

        array[wasp.waspmoteid] = aux
        aux = None
        flag = False
    context = {'waspmote_info': waspmote_info,
               'array': array}
    return render(request, 'AgriculturaPrecisao.html', context)


def get_100values(request):
    if request.is_ajax():
        if request.method == 'GET':
            incoming_json = request.GET['sensorId']
            aux_list = re.findall('\d+', incoming_json)  # Buscar o id do sensor
            sensor_id = int(
                ''.join(map(str, aux_list)))  # O id do sensor vem numa lista, isto serve para o meter num int
            values = Sensorval.objects.filter(sensor_fk=sensor_id)[::-1][:100]
            data = serializers.serialize("json", values)
            return HttpResponse(data, content_type="application/json")

    else:
        return HttpResponse(json.dumps({"error": "error"}),
                            content_type="application/json")


def get_1000values(request):
    if request.is_ajax():
        if request.method == 'GET':
            incoming_json = request.GET['sensorId']
            aux_list = re.findall('\d+', incoming_json)  # Buscar o id do sensor
            sensor_id = int(
                ''.join(map(str, aux_list)))  # O id do sensor vem numa lista, isto serve para o meter num int
            valuesmonth = Sensorval.objects.filter(sensor_fk=sensor_id)[::-1][:1000]
            datamonth = serializers.serialize("json", valuesmonth)
            return HttpResponse(datamonth, content_type="application/json")
    else:
        return HttpResponse(json.dumps({"error": "error"}),
                            content_type="application/json")


def get_customdayvalues(request):
    array = []
    if request.is_ajax():
        if request.method == 'GET':
            incoming_json = request.GET['sensorId']
            incoming_json2 = request.GET['date']
            aux_list = re.findall('\d+', incoming_json)  # Buscar o id do sensor
            sensor_id = int(
                ''.join(map(str, aux_list)))  # O id do sensor vem numa lista, isto serve para o meter num int
            valuesall = Sensorval.objects.filter(sensor_fk=sensor_id)
            for val in valuesall:
                datac = val.timestamp.strftime('%Y-%m-%d')
                if datac == incoming_json2:
                    array.append(val)
            datavalues = serializers.serialize("json", array)
            return HttpResponse(datavalues, content_type="application/json")
    else:
        return HttpResponse(json.dumps({"error": "error"}),
                            content_type="application/json")


def get_customintervalvalues(request):
    array = []
    if request.is_ajax():
        if request.method == 'GET':
            incoming_json = request.GET['sensorId']
            incoming_json2 = request.GET['dateini']
            incoming_json3 = request.GET['datefim']
            aux_list = re.findall('\d+', incoming_json)  # Buscar o id do sensor
            sensor_id = int(
                ''.join(map(str, aux_list)))  # O id do sensor vem numa lista, isto serve para o meter num int
            valuesall = Sensorval.objects.filter(sensor_fk=sensor_id)

            for val in valuesall:
                datac = val.timestamp.strftime('%Y-%m-%d')
                if incoming_json2 <= datac <= incoming_json3:
                    array.append(val)
            datavalues = serializers.serialize("json", array)
            return HttpResponse(datavalues, content_type="application/json")
    else:
        return HttpResponse(json.dumps({"error": "error"}),
                            content_type="application/json")


def get_typesensor(request):
    if request.is_ajax():
        if request.method == 'GET':
            sensor_id = request.GET['sensorid']
            typesensor = Typesensor.objects.get(sensor__sensorid=sensor_id).typesensorname
            typesensorlib = Typesensor.objects.get(sensor__sensorid=sensor_id).sensornamelib
            jsonResponse = json.dumps({'typesensor': typesensor, 'typesensorlib': typesensorlib})
            return HttpResponse(jsonResponse, content_type="application/json")
    else:
        return HttpResponse(json.dumps({"error": "error"}),
                            content_type="application/json")


def validate_login(request):
    if request.method == 'POST':
        username = str(request.POST.get('username'))
        print(username)
        pwd = str(request.POST.get('password'))
        print(pwd)
        user = User.objects.get(username=username, password=pwd)
        if user is None:
            return render(request, 'index.html')
        else:
            request.session['userID'] = user.iduser
            request.session['username'] = user.username
            url = reverse('appkeys', args=())
            return HttpResponseRedirect(url)


def appkeys(request):
    appkey_info = Appkey.objects.filter(userid=request.session['userID'])
    waspmote_info = Waspmote.objects.filter(appkeyid=appkey_info)
    context = {'appkey_info': appkey_info, 'waspmote_info': waspmote_info}
    return render(request, 'Appkeys.html', context)


def logout(request):
    request.session.clear()
    return render(request, 'index.html')


def navbar(request):
    return render(request, 'navbar.html')


def test(request):
    return render(request, 'teste.html')


def realtime(request):
    user_id = request.session['userID']
    app_info = Appkey.objects.filter(userid=user_id)
    waspmote_info = Waspmote.objects.filter(appkeyid__userid=user_id)
    sensor_info = Sensor.objects.filter(waspmoteid__appkeyid__userid=user_id).order_by('waspmoteid__appkeyid',
                                                                                       'waspmoteid')
    context = {'sensor_info': sensor_info, 'app_info': app_info, 'waspmote_info': waspmote_info}
    return render(request, 'realtime.html', context)


def config(request):
    return render(request, 'config.html')


class UserViewSet(viewsets.ModelViewSet):
    """
    API endpoint that allows users to be viewed or edited.
    """
    queryset = User.objects.all()

templates/Appkeys.html
<!DOCTYPE html>
<html lang="en" xmlns="http://www.w3.org/1999/html">
<head>
    <meta charset="UTF-8">
    <title>Página das Appkeys</title>

    {% load staticfiles %}

    <!-- Bootstrap Core CSS -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <!-- Custom CSSTest -->
    <link href="{% static 'css/testeCss.css' %}" rel="stylesheet">
    <!-- Custom CSS -->
    <link href="{% static 'css/sb-admin-2.css' %}" rel="stylesheet">
    <!-- Custom Fonts -->
    <link href="{% static 'css/font-awesome.min.css' %}" rel="stylesheet" type="text/css">
    <!-- MetisMenu CSS -->
    <link href="{% static 'css/metisMenu.min.css' %}" rel="stylesheet">

    <link href="{% static 'css/timeline.css' %}" rel="stylesheet">

    <link href="{% static 'css/jquery-ui.css' %}" rel="stylesheet">

    <link href="{% static 'css/style.css' %}" rel="stylesheet">
    <script src="{% static 'js/jquery.js' %}"></script>
</head>
<body>
<div id="includedContent">
    <script>
        $("#includedContent").load("{% url 'navbar' %}");
    </script>
</div>

<!--USAR O QUE ESTA PARA BAIXO-->
<div class="container-fluid" style="display: inline">
    <div class="row">
        {% for app in appkey_info %}
            <div class="appkeysboard" style="margin-top: 1%">

                <div class="col-md-1">
                    <i class="fa fa-key fa-5x centerthings"
                       style="margin-top: 40%;font-size: 120px; margin-left: 20px"></i>

                </div>
                <div class="col-md-2" style="margin-left: 1%">
                    <h2 style="text-align: center; margin-top: 30%">AppKey <p
                            style="padding: 3%; font-weight: bold;">{{ app.appkey }}</p></h2>
                </div>
                <div class="col-md-3" style="margin-right: -30px">
                    <div class="row">
                        <div style="margin-left: 70px"><h2>Waspmotes</h2></div>
                        <table id="tablegen" style="width: 500px;">
                            {% for wasps in app.waspmote_set.all %}
                                <tr>
                                    <td><h5>{{ wasps.waspmote_name }}</h5></td>
                                </tr>
                            {% endfor %}
                        </table>
                    </div>
                </div>
                <div class="col-md-5" style="margin-right: -30px">
                    <div class="row">
                        <div style="margin-left: 70px"><h2>Lista de sensores</h2></div>
                        <table id="tablegen" style="width: 500px;">
                            {% for wasps in app.waspmote_set.all %}
                                {% for sens in wasps.sensor_set.all %}
                                    <tr class="col-md-4">
                                        <td><h5>{{ sens.typesensorid.typesensorname }}</h5></td>
                                    </tr>
                                    {# <div class="tabletwo">{{ sens.typesensorid.typesensorname }}</div>#}

                                {% endfor %}
                            {% endfor %}
                        </table>
                    </div>
                </div>
                <div class="col-md-1">
                    <a href="{% url 'agricprecisao' %}?appId={{ app.appkeyid }}" id="appkey{{ app.appkeyid }}">
                        <span class="pull-right"><i class="fa fa-arrow-circle-right"
                                                    style="color: #737373; font-size: 120px; margin-top: 40%;"> </i></span>
                    </a>
                </div>
            </div>
            {#        <div class="col-lg-4 col-lg-offset-1">#}
            {#        <div class="panel panel-primary">#}
            {#            <div class="panel-heading">#}
            {#                <div class="row">#}
            {#                    <div class="col-xs-3">#}
            {#                        <i class="fa fa-key fa-5x"></i>#}
            {#                    </div>#}
            {#                        <div class="col-xs-9 text-right">#}
            {#                            <div><h2>AppKey nº {{ app.appkey }}</h2></div>#}
            {#                        </div>#}
            {#                </div>#}
            {#            </div>#}
            {#            <a href="{% url 'agricprecisao' %}?appId={{app.appkeyid}}" id="appkey{{ app.appkeyid }}">#}
            {#                 <div class="panel-footer">#}
            {#                    <span class="pull-left">Ver os respetivos waspmotes</span>#}
            {#                    <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>#}
            {#                    <div class="clearfix"></div>#}
            {#                </div>#}
            {#            </a>#}
            {#        </div>#}
            {#        </div>#}
        {% endfor %}
    </div>
</div>
</body>
<script src="{% static 'js/hours.js' %}"></script>
<script src="{% static 'js/mqttws31.js' %}" type="text/javascript"></script>

<script src="http://code.highcharts.com/stock/highstock.js"></script>
<script src="http://code.highcharts.com/stock/modules/exporting.js"></script>
<!-- jQuery -->

<script src="{% static 'js/jquery-ui.js' %}"></script>
<script type="text/javascript" src="{% static 'js/jquery.canvasjs.min.js' %}"></script>
<script type="text/javascript" src="{% static 'js/loading.js' %}"></script>
<script src="{% static 'js/knockout-3.4.0.js' %}"></script>
<!-- Bootstrap Core JavaScript -->
<script src="{% static 'js/bootstrap.min.js' %}"></script>
<!-- Metis Menu Plugin JavaScript -->
<script src="{% static 'js/metisMenu.min.js' %}"></script>
<!-- Morris Charts JavaScript -->
<script src="{% static 'js/raphael-min.js' %}"></script>
<!-- Custom Theme JavaScript -->
<script src="{% static 'js/sb-admin-2.js' %}"></script>

<script src="{% static 'js/dashboard.js' %}"></script>


</html>

templates/Perfil.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ username }}</title>

    {% load staticfiles %}

    <!-- Bootstrap Core CSS -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <!-- Custom CSSTest -->
    <link href="{% static 'css/testeCss.css' %}" rel="stylesheet">
    <!-- Custom CSS -->
    <link href="{% static 'css/sb-admin-2.css' %}" rel="stylesheet">
    <!-- Custom Fonts -->
    <link href="{% static 'css/font-awesome.min.css' %}" rel="stylesheet" type="text/css">
    <!-- MetisMenu CSS -->
    <link href="{% static 'css/metisMenu.min.css' %}" rel="stylesheet">

    <link href="{% static 'css/timeline.css' %}" rel="stylesheet">

    <link href="{% static 'css/jquery-ui.css' %}" rel="stylesheet">

    <link href="{% static 'css/style.css' %}" rel="stylesheet">
    <link rel="stylesheet" href="http://netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.min.css"/>
</head>
<body>
<div class="container" style="background-color: #FFFFFF; padding: 2%">
    <div class="row">
        <div class="col-md-10"><h1 style="font-size: 50px; margin-left: 2%" class="username_h1" id="{{ username }}">
            Perfil
            de {{ username }}</h1></div>
        <div id="close" class="col-md-2" style="text-align: right; padding-right: 4%; padding-top: 1% ">
            <a href="#" class="fa fa-times fa-4x" style="color: #2b2b2b; text-decoration: none" id="closePerfil"></a>
        </div>
    </div>
    <div class="row col-md-7">
        <div class="row container col-md-8" style="padding: 1%; margin-bottom: 2%">
            <div class="col-md-4" style="font-size: 20px;">Nome :</div>
            <div class="col-md-6" style="font-size: 20px;"> {{ name }}</div>
        </div>
        <div class="row container col-md-8" style="padding: 1%; margin-bottom: 2%">
            <div class="col-md-5" style="font-size: 20px;">Username :</div>
            <div class="col-md-6" style="font-size: 20px;"> {{ username }}</div>
        </div>
        <div class="row container col-md-8" style="padding: 1%">
            <div class="col-md-4" style="font-size: 20px;">Password :</div>
            <div class="col-md-6" style="font-size: 20px;">**********</div>
            <div class="col-md-2">
                <button id="password" class="btn btn-default updateBtn" data-toggle="modal" data-target="#myModal_pass">
                    Editar
                </button>
            </div>
        </div>
        <div class="row container col-md-8" style="padding: 1%">
            <div class="col-md-4" style="font-size: 20px;">País :</div>
            <div class="col-md-6" style="font-size: 20px;"> {{ country }}</div>
            <div class="col-md-2">
                <button id="country" class="btn btn-default updateBtn" data-toggle="modal" data-target="#myModal">
                    Editar
                </button>
            </div>
        </div>
        <div class="row container col-md-8" style="padding: 1%">
            <div class="col-md-4" style="font-size: 20px;">Cidade :</div>
            <div class="col-md-6" style="font-size: 20px;"> {{ city }}</div>
            <div class="col-md-2">
                <button id="city" class="btn btn-default updateBtn" data-toggle="modal" data-target="#myModal">Editar
                </button>
            </div>
        </div>
        <div class="row container col-md-8" style="padding: 1%">
            <div class="col-md-4" style="font-size: 20px;">Email :</div>
            <div class="col-md-6" style="font-size: 20px;"> {{ mail }}</div>
            <div class="col-md-2">
                <button id="mail" class="btn btn-default updateBtn" data-toggle="modal" data-target="#myModal">Editar
                </button>
            </div>
        </div>
        <div class="row container col-md-8" style="padding: 1%">
            <div class="col-md-4" style="font-size: 20px;">Telemóvel :</div>
            <div class="col-md-6" style="font-size: 20px;"> {{ phone }}</div>
            <div class="col-md-2">
                <button id="phone" class="btn btn-default updateBtn" data-toggle="modal" data-target="#myModal">Editar
                </button>
            </div>
        </div>
    </div>
    <div class="row col-md-4">
        <div style="font-size: 35px; padding: 2%; text-align: center">Appkeys</div>
        {% for app in appk %}
            <div class="row" style="font-size: 25px; padding: 5%">
                <div class="fa fa-chevron-right"></div>
                {{ app.appkey }}
            </div>
            {% for wasp in app.waspmote_set.all %}
                <div style="font-size: 18px; padding: 2%; margin-left: 10%">
                    <div class="fa fa-cube fa-lg"></div>
                    {{ wasp.waspmote_name }}
                </div>
            {% endfor %}
        {% endfor %}
    </div>
</div>
<!-- Password Modal -->
<div class="modal fade" id="myModal_pass" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-body">
                <div class="form-group">
                    <fieldset>

                        <label for="actualPassInput">Password Atual</label>
                        <input type="password" id="actualPassInput" class="form-control">
                        <label for="new_passInput">Nova Password</label>
                        <input type="password" class="form-control" id="newPassInput">
                    </fieldset>
                    <div class="modal-footer">
                        <button type="submit" class="btn btn-primary saveBtn" id="passInput">Atualizar</button>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<!-- Not Password Modal -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-body">
                <div class="form-group">
                    <fieldset>
                        <label for="new_input">Novo Valor</label>
                        <input type="text" class="form-control" id="newInput">
                    </fieldset>
                    <div class="modal-footer">
                        <button type="submit" class="btn btn-primary saveBtn" id="normalInput">Atualizar</button>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>


</body>
<!-- jQuery -->
<script src="{% static 'js/jquery.js' %}"></script>
<script src="{% static 'js/jquery-ui.js' %}"></script>
<script type="text/javascript" src="{% static 'js/jquery.canvasjs.min.js' %}"></script>
<script src="{% static 'js/knockout-3.4.0.js' %}"></script>
<!-- Bootstrap Core JavaScript -->
<script src="{% static 'js/bootstrap.min.js' %}"></script>
<!-- Metis Menu Plugin JavaScript -->
<script src="{% static 'js/metisMenu.min.js' %}"></script>
<!-- Morris Charts JavaScript -->
<script src="{% static 'js/raphael-min.js' %}"></script>
<!-- Custom Theme JavaScript -->
<script src="{% static 'js/perfil.js' %}"></script>
<!-- Plugin JavaScript -->
<script src="{% static 'js/jquery.easing.min.js' %}"></script>
</html>

templates/config.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Config</title>
</head>
<body>

</body>
</html>

templates/register.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Página de Registo</title>
</head>
<body>

</body>
</html>